In [37]:
import numpy as np
import pandas as pd



In [16]:
#Using NumPy, create two 5 by 5 arrays.  Use rand rather than randint. Follow the steps below:
array1=np.random.rand(5,5)
array2=np.random.rand(5,5)


[[0.72367106 0.79685643 0.0047381  0.59347238 0.0038687 ]
 [0.95717356 0.02089598 0.0082406  0.26722036 0.16375364]
 [0.57895422 0.84430284 0.90247128 0.53526497 0.66181614]
 [0.93647135 0.2734427  0.20249499 0.45292608 0.66458153]
 [0.32940519 0.89229535 0.29438708 0.99155892 0.93207118]]
[[0.53764393 0.14825784 0.9914738  0.93343537 0.36393919]
 [0.77655654 0.98483016 0.1516732  0.83304908 0.6737516 ]
 [0.5254848  0.11171411 0.86375821 0.87517688 0.84484875]
 [0.02789066 0.81907433 0.35143995 0.43751259 0.30170951]
 [0.19055541 0.49786279 0.76363939 0.41019085 0.74172711]]


In [17]:
# a- Add these matrices together (display results)
sum_ar=array1+array2
print(sum_ar)

[[1.26131499 0.94511427 0.99621191 1.52690775 0.36780788]
 [1.73373009 1.00572614 0.15991379 1.10026944 0.83750524]
 [1.10443902 0.95601695 1.7662295  1.41044185 1.50666489]
 [0.96436201 1.09251703 0.55393494 0.89043867 0.96629104]
 [0.51996061 1.39015814 1.05802647 1.40174976 1.67379828]]


In [20]:
# b- Multiply the matrices using element-wise (Hadamard) multiplication and store results in another array
mult_ar=array1*array2


In [54]:
# c- Take the result of the above step and flatten the array and store the result in another array
flatten_ar=mult_ar.flatten()
print(flatten_ar)

[0.38907736 0.11814021 0.0046977  0.55396811 0.00140797 0.74329938
 0.020579   0.00124988 0.22260767 0.11032927 0.30423164 0.09432054
 0.77951698 0.46845153 0.55913454 0.02611881 0.2239699  0.07116483
 0.19816086 0.20051057 0.06276994 0.44424066 0.22480557 0.40672839
 0.69134246]


In [27]:
 #d- Display the STD and mean of the result in the last step
print(np.std(flatten_ar))
print(np.mean(flatten_ar))

0.24022872897564534
0.27683295070466424


In [42]:
#Create a Pandas dataframe 
#a- Go to this site: https://www.chess.com/players
#b- Take the top 5 players and add them to a dictionary. 
#Create entries for name, country, score and rank#. The score is the number to the left of the rank #

dict_chess={'name':["Magnus Carlsen","Fabiano Caruana","Hikaru Nakamura","Ian Nepomniachtchi","Nodirbek Abdusattorov"],
            'country':["Norway","United States","United States","Russia","Uzbekistan"],
            'score':[2830,2804,2781,2766,2766],
            'rank':[1,2,3,4,4]}
print(dict_chess)

{'name': ['Magnus Carlsen', 'Fabiano Caruana', 'Hikaru Nakamura', 'Ian Nepomniachtchi', 'Nodirbek Abdusattorov'], 'country': ['Norway', 'United States', 'United States', 'Russia', 'Uzbekistan'], 'score': [2830, 2804, 2781, 2766, 2766], 'rank': [1, 2, 3, 4, 4]}


In [46]:
#c-Add the dictionary to a dataframe
chessdf=pd.DataFrame(dict_chess)
print(chessdf)

                    name        country  score  rank
0         Magnus Carlsen         Norway   2830     1
1        Fabiano Caruana  United States   2804     2
2        Hikaru Nakamura  United States   2781     3
3     Ian Nepomniachtchi         Russia   2766     4
4  Nodirbek Abdusattorov     Uzbekistan   2766     4


In [52]:
#d-Add to the dataframe: add the 6th best player to the dataframe, also using a data dictionary
sixth_player={'name':"Ding Liren",'country':"China",'score':2762,'rank':6}
chessdf=pd.concat([chessdf,pd.DataFrame([sixth_player])],ignore_index = True)


In [53]:
print(chessdf)

                    name        country  score  rank
0         Magnus Carlsen         Norway   2830     1
1        Fabiano Caruana  United States   2804     2
2        Hikaru Nakamura  United States   2781     3
3     Ian Nepomniachtchi         Russia   2766     4
4  Nodirbek Abdusattorov     Uzbekistan   2766     4
5             Ding Liren          China   2762     6
